---
title: "EX03-SP Dijkstra Algorithm"
author: "Alberto Maximiliano Correa Pietrobon"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
```

## Setup del Grafo
```{r SetupGrafo}
#Grafo con Nodos={S,2,3,4,5,T} Arcos = {(S,2);(S,3);(2,4);(2,T);(3,5);(4,T);(5,T) Pesos={2,2,2,5,2,1,2}
Nodos<-c(1:6)
DFGrafo<- data.frame(Origen=c(1,1,2,2,3,4,5),Destino=c(2,3,4,6,5,6,6),Pesos=c(2,2,2,5,2,1,2))
NdoInicial<-1
NdoFinal<-6
NdoActual<-NdoInicial
NdoAnterior<-0
```

## Inicializacion de Tablas de Precedencias y Pesos
```{r Inicializacion}
DFPesos<-data.frame(I0Peso=c(0,rep(Inf,length(Nodos)-1)), row.names = Nodos)
DFPrece<-data.frame(I0Prec=rep(NA,6), row.names = Nodos)
NdoVisitados<-c(NdoInicial)
```

## Interaciones a traves del grafo
```{r cicloIteraciones}
#Comienzo Ciclo de Iteraciones
while (NdoActual!=NdoFinal) {
  ##VectoresPrecedentes
  WhereNdoDest<-as.vector(which(DFGrafo$Origen==NdoActual, arr.ind = TRUE))
  NdoDest<-c(DFGrafo[WhereNdoDest,"Destino"])
  PesoNdoDest<-c(DFGrafo[WhereNdoDest,"Pesos"])
  NdoOrigen<-c(DFGrafo[WhereNdoDest,"Origen"])

  #copioAnterior
  AIT_W<-paste("I",NdoAnterior,"Peso",sep = "")
  AIT_P<-paste("I",NdoAnterior,"Prec",sep = "")
  NIT_W<-paste("I",NdoActual,"Peso",sep = "")
  NIT_P<-paste("I",NdoActual,"Prec",sep = "")
  
  DFPesos[NIT_W]<-DFPesos[AIT_W]
  DFPrece[NIT_P]<-DFPrece[AIT_P]
  
  for (i in 1:length(Nodos)){
    
    if (NdoInicial==i) {NdoVisitados<-c(NdoInicial)} else {NdoVisitados<-c(NdoVisitados,NdoActual)} 

    if (any(i == NdoVisitados)){DFPesos[i,NIT_W]<-NaN ; DFPrece[i,NIT_P]<-NaN}
  
    
    for (k in WhereNdoDest) {
      VOrigen<-DFGrafo[k,"Origen"]
      VDestino<-DFGrafo[k,"Destino"]
      Dacu<-DFPesos[NdoActual,AIT_W]+DFGrafo[k,"Pesos"]
      #Dest<-DFGrafo[k,"Destino"]
      if (Dacu<DFPesos[VDestino,AIT_W]) {DFPesos[VDestino,NIT_W]<-Dacu; DFPrece[VDestino,NIT_P]<-VOrigen}
      }
  }  
  #ActualizoDatos  
  NdoAnterior<-NdoActual
  NdoActual<-NdoActual+1
  
}

#Tabla Final de Pesos
print(DFPesos, quote = TRUE, row.names = TRUE)

#Tabla Final de Precedencias
print(DFPrece, quote = TRUE, row.names = TRUE)
```

## Presentacion de Resultados
```{R Resultados, warning=FALSE}
PesoFinal<-which.min(DFPesos[NdoFinal,])

CMC<-c(NdoFinal, max(DFPrece[NdoFinal,], na.rm = TRUE))
w<-min(CMC)
while (w>0) {
CMC<-c(CMC,max(DFPrece[w,], na.rm = TRUE))
w<-min(CMC)
}

print(paste("El Camino mas corto es",CMC,sep = " "))

print(paste("El Peso del camino mas corto es",PesoFinal,sep = " "))
```






















